# Mysql
# :db: mysql://user@localhost/db-name

# Sqlite3
# :db: sqlite3:///path/to/db-name.db'

:development:
  :db: 'sqlite3::memory:'
  :auth:
    :username: 'admin'
    :password: 'schwarz'
  

:test: 
  :db: 'sqlite3::memory:'
  :auth:
    :username: 'admin'
    :password: 'schwarz'
  
    
:production:
  :db:
  :auth:
    :username: 'admin'
    :password: 'schwarz'

